### ISSUE TITLE
Schedule a time range where AlarmSystem is disarmed  

### ISSUE THREAD

**Issue by vpomax** [runningman84/home-assistant-apps#6]
Currently AlarmSystem is armed every time for x minutes if no presence is detected inside the house.
But there are situations where it is necessary that AlarmSystem to remain disarmed for example between 2:00 pm and 6:00 pm even if no presence is detected at home., or you can program that every Wednesday remains disarmed between 14:00 and 18:00.
Is it possible to schedule a period of time for a given day or for every day during which Alarm System remains disarmed for both the home and away function?

**Comment by runningman84** [comment]
Right now there is no such feature in my code, but you can disable the whole app during this timeframe which would produce the same result.

**Comment by runningman84** [comment]
Otherwise feel free to create a pull request for this feature.

**Comment by runningman84** [comment]
There is a new feature which allows to auto arm_home within a specific timeframe.

Btw. you could just use a normal home assistant automation which would tun on the guest_mode in this time frame. This would mean no automatic arming of the system would happen. I think this is the most flexible solution. Because you can create multiple timeframes quite easily.
